:- module(dental_questions, [question/6, valid_answer/2, expand_observations/2]).

% Shared UI schema. These records are not counted as domain facts.
question(age,setup,select,'Age in completed years',[option('unknown','Unknown'),option(0,'0'),option(1,'1'),option(2,'2'),option(3,'3'),option(4,'4'),option(5,'5'),option(6,'6'),option(7,'7'),option(8,'8'),option(9,'9'),option(10,'10'),option(11,'11'),option(12,'12'),option(13,'13'),option(14,'14'),option(15,'15'),option(16,'16'),option(17,'17'),option(18,'18'),option(19,'19'),option(20,'20'),option(21,'21'),option(22,'22'),option(23,'23'),option(24,'24'),option(25,'25'),option(26,'26'),option(27,'27'),option(28,'28'),option(29,'29'),option(30,'30'),option(31,'31'),option(32,'32'),option(33,'33'),option(34,'34'),option(35,'35'),option(36,'36'),option(37,'37'),option(38,'38'),option(39,'39'),option(40,'40'),option(41,'41'),option(42,'42'),option(43,'43'),option(44,'44'),option(45,'45'),option(46,'46'),option(47,'47'),option(48,'48'),option(49,'49'),option(50,'50'),option(51,'51'),option(52,'52'),option(53,'53'),option(54,'54'),option(55,'55'),option(56,'56'),option(57,'57'),option(58,'58'),option(59,'59'),option(60,'60'),option(61,'61'),option(62,'62'),option(63,'63'),option(64,'64'),option(65,'65'),option(66,'66'),option(67,'67'),option(68,'68'),option(69,'69'),option(70,'70'),option(71,'71'),option(72,'72'),option(73,'73'),option(74,'74'),option(75,'75'),option(76,'76'),option(77,'77'),option(78,'78'),option(79,'79'),option(80,'80'),option(81,'81'),option(82,'82'),option(83,'83'),option(84,'84'),option(85,'85'),option(86,'86'),option(87,'87'),option(88,'88'),option(89,'89'),option(90,'90'),option(91,'91'),option(92,'92'),option(93,'93'),option(94,'94'),option(95,'95'),option(96,'96'),option(97,'97'),option(98,'98'),option(99,'99'),option(100,'100'),option(101,'101'),option(102,'102'),option(103,'103'),option(104,'104'),option(105,'105'),option(106,'106'),option(107,'107'),option(108,'108'),option(109,'109'),option(110,'110'),option(111,'111'),option(112,'112'),option(113,'113'),option(114,'114'),option(115,'115'),option(116,'116'),option(117,'117'),option(118,'118'),option(119,'119'),option(120,'120')],always).
question(dentition,setup,select,'Dentition',[option('unknown','Unknown'),option('primary','Primary'),option('mixed','Mixed'),option('permanent','Permanent'),option('na','Not applicable')],always).
question(tooth_type,setup,select,'Affected tooth type',[option('unknown','Unknown'),option('primary','Primary tooth'),option('permanent','Permanent tooth'),option('na','Not applicable')],always).
question(tooth,setup,select,'Affected tooth',[option('unknown','Unknown'),option(11,'FDI 11'),option(12,'FDI 12'),option(13,'FDI 13'),option(14,'FDI 14'),option(15,'FDI 15'),option(16,'FDI 16'),option(17,'FDI 17'),option(18,'FDI 18'),option(21,'FDI 21'),option(22,'FDI 22'),option(23,'FDI 23'),option(24,'FDI 24'),option(25,'FDI 25'),option(26,'FDI 26'),option(27,'FDI 27'),option(28,'FDI 28'),option(31,'FDI 31'),option(32,'FDI 32'),option(33,'FDI 33'),option(34,'FDI 34'),option(35,'FDI 35'),option(36,'FDI 36'),option(37,'FDI 37'),option(38,'FDI 38'),option(41,'FDI 41'),option(42,'FDI 42'),option(43,'FDI 43'),option(44,'FDI 44'),option(45,'FDI 45'),option(46,'FDI 46'),option(47,'FDI 47'),option(48,'FDI 48'),option(51,'FDI 51'),option(52,'FDI 52'),option(53,'FDI 53'),option(54,'FDI 54'),option(55,'FDI 55'),option(61,'FDI 61'),option(62,'FDI 62'),option(63,'FDI 63'),option(64,'FDI 64'),option(65,'FDI 65'),option(71,'FDI 71'),option(72,'FDI 72'),option(73,'FDI 73'),option(74,'FDI 74'),option(75,'FDI 75'),option(81,'FDI 81'),option(82,'FDI 82'),option(83,'FDI 83'),option(84,'FDI 84'),option(85,'FDI 85'),option('na','Not applicable')],always).
question(region,setup,select,'Affected region',[option('unknown','Unknown'),option('single_tooth','Single tooth'),option('multiple_teeth','Multiple teeth'),option('general_gums','Generalized gums'),option('anterior_gums','Anterior gums'),option('jaw_joint','Jaw joint'),option('na','Not applicable')],always).
question(second_tooth,setup,select,'Second affected tooth',[option('unknown','Unknown'),option(11,'FDI 11'),option(12,'FDI 12'),option(13,'FDI 13'),option(14,'FDI 14'),option(15,'FDI 15'),option(16,'FDI 16'),option(17,'FDI 17'),option(18,'FDI 18'),option(21,'FDI 21'),option(22,'FDI 22'),option(23,'FDI 23'),option(24,'FDI 24'),option(25,'FDI 25'),option(26,'FDI 26'),option(27,'FDI 27'),option(28,'FDI 28'),option(31,'FDI 31'),option(32,'FDI 32'),option(33,'FDI 33'),option(34,'FDI 34'),option(35,'FDI 35'),option(36,'FDI 36'),option(37,'FDI 37'),option(38,'FDI 38'),option(41,'FDI 41'),option(42,'FDI 42'),option(43,'FDI 43'),option(44,'FDI 44'),option(45,'FDI 45'),option(46,'FDI 46'),option(47,'FDI 47'),option(48,'FDI 48'),option(51,'FDI 51'),option(52,'FDI 52'),option(53,'FDI 53'),option(54,'FDI 54'),option(55,'FDI 55'),option(61,'FDI 61'),option(62,'FDI 62'),option(63,'FDI 63'),option(64,'FDI 64'),option(65,'FDI 65'),option(71,'FDI 71'),option(72,'FDI 72'),option(73,'FDI 73'),option(74,'FDI 74'),option(75,'FDI 75'),option(81,'FDI 81'),option(82,'FDI 82'),option(83,'FDI 83'),option(84,'FDI 84'),option(85,'FDI 85'),option('na','Not applicable')],when(region,multiple_teeth)).
question(focus,setup,select,'Assessment focus',[option('full','Full assessment'),option('tooth','Tooth pain'),option('gums','Gum symptoms')],always).
question(tooth_pain,symptoms,radio,'Is tooth pain present?',[option('unknown','Unknown'),option('yes','Yes'),option('no','No'),option('na','Not applicable')],always).
question(pain_severity,symptoms,select,'Pain severity',[option('unknown','Unknown'),option('mild','Mild'),option('moderate','Moderate'),option('severe','Severe'),option('na','Not applicable')],when(tooth_pain,yes)).
question(symptom_duration,symptoms,select,'Symptom duration',[option('unknown','Unknown'),option('days','1-7 days'),option('weeks','1-4 weeks'),option('months','1-6 months'),option('long_term','Over 6 months'),option('na','Not applicable')],always).
question(triggers,symptoms,multi,'What triggers the tooth pain?',[option('unknown','Unknown'),option('cold','Cold'),option('sweet','Sweet'),option('hot','Hot'),option('biting','Biting'),option('none','None'),option('na','Not applicable')],when(tooth_pain,yes)).
question(persistence,symptoms,select,'Pain after the trigger stops',[option('unknown','Unknown'),option('brief','Brief; stops promptly'),option('lingering','Lingering; continues'),option('episodic','Unprovoked episodes'),option('na','Not applicable')],when(tooth_pain,yes)).
question(spontaneous,symptoms,radio,'Spontaneous tooth pain?',[option('unknown','Unknown'),option('yes','Yes'),option('no','No'),option('na','Not applicable')],always).
question(sleep_pain,symptoms,radio,'Tooth pain interrupts sleep?',[option('unknown','Unknown'),option('yes','Yes'),option('no','No'),option('na','Not applicable')],always).
question(biting_pain,symptoms,radio,'Pain when biting?',[option('unknown','Unknown'),option('yes','Yes'),option('no','No'),option('na','Not applicable')],always).
question(gum_bleeding,symptoms,radio,'Bleeding during brushing or flossing?',[option('unknown','Unknown'),option('yes','Yes'),option('no','No'),option('na','Not applicable')],always).
question(red_gums,symptoms,radio,'Red or swollen gum margins?',[option('unknown','Unknown'),option('yes','Yes'),option('no','No'),option('na','Not applicable')],always).
question(gum_tenderness,symptoms,radio,'Gum tenderness?',[option('unknown','Unknown'),option('yes','Yes'),option('no','No'),option('na','Not applicable')],always).
question(facial_swelling,symptoms,radio,'Facial swelling?',[option('unknown','Unknown'),option('yes','Yes'),option('no','No'),option('na','Not applicable')],always).
question(drainage,symptoms,radio,'Pus or drainage?',[option('unknown','Unknown'),option('yes','Yes'),option('no','No'),option('na','Not applicable')],always).
question(fever,symptoms,radio,'Fever reported?',[option('unknown','Unknown'),option('yes','Yes'),option('no','No'),option('na','Not applicable')],always).
question(jaw_clicking,symptoms,radio,'Jaw clicking?',[option('unknown','Unknown'),option('yes','Yes'),option('no','No'),option('na','Not applicable')],always).
question(history,history,multi,'Relevant history',[option('unknown','Unknown'),option('trauma','Recent trauma'),option('restoration','Recent restoration'),option('extraction','Recent extraction'),option('pulp_treatment','Previous pulp treatment'),option('diabetes','Known diabetes'),option('smoking','Smoking'),option('none','None reported'),option('na','Not applicable')],always).
question(cavity,examination,radio,'Cavitated lesion observed?',[option('unknown','Unknown'),option('yes','Yes'),option('no','No'),option('na','Not applicable')],always).
question(soft_tissue,examination,radio,'Softened tooth tissue observed?',[option('unknown','Unknown'),option('yes','Yes'),option('no','No'),option('na','Not applicable')],always).
question(discoloration,examination,radio,'Decay-related surface discoloration?',[option('unknown','Unknown'),option('yes','Yes'),option('no','No'),option('na','Not applicable')],always).
question(fracture,examination,radio,'Visible tooth fracture?',[option('unknown','Unknown'),option('yes','Yes'),option('no','No'),option('na','Not applicable')],always).
question(root_maturity,examination,select,'Permanent root maturity',[option('unknown','Unknown'),option('immature','Immature'),option('mature','Mature'),option('na','Not applicable')],when(tooth_type,permanent)).
question(thermal_response,examination,select,'Recorded thermal response',[option('unknown','Unknown'),option('brief','Brief response'),option('lingering','Exaggerated, lingering response'),option('absent','No response'),option('na','Not applicable')],all([when(tooth_type,permanent),when(root_maturity,mature)])).
question(electric_response,examination,select,'Recorded electric response',[option('unknown','Unknown'),option('present','Response present'),option('absent','No response'),option('na','Not applicable')],all([when(tooth_type,permanent),when(root_maturity,mature)])).
question(percussion,examination,radio,'Percussion or palpation tenderness?',[option('unknown','Unknown'),option('yes','Yes'),option('no','No'),option('na','Not applicable')],always).
question(mobility,examination,radio,'Abnormal tooth mobility?',[option('unknown','Unknown'),option('yes','Yes'),option('no','No'),option('na','Not applicable')],always).
question(radiographic_caries,examination,radio,'Dentist-interpreted coronal carious lesion?',[option('unknown','Unknown'),option('yes','Yes'),option('no','No'),option('na','Not applicable')],always).
question(apical_pathology,examination,radio,'Apical/furcation pathology or pathological resorption?',[option('unknown','Unknown'),option('yes','Yes'),option('no','No'),option('na','Not applicable')],always).
question(plaque,periodontal,radio,'Plaque or calculus present?',[option('unknown','Unknown'),option('yes','Yes'),option('no','No'),option('na','Not applicable')],always).
question(prior_destruction,periodontal,radio,'Previous periodontal destruction?',[option('unknown','Unknown'),option('yes','Yes'),option('no','No'),option('na','Not applicable')],always).
question(pocket_mm,periodontal,select,'Maximum probing depth',[option('unknown','Unknown'),option(0,'0 mm'),option(0.5,'0.5 mm'),option(1,'1 mm'),option(1.5,'1.5 mm'),option(2,'2 mm'),option(2.5,'2.5 mm'),option(3,'3 mm'),option(3.5,'3.5 mm'),option(4,'4 mm'),option(4.5,'4.5 mm'),option(5,'5 mm'),option(5.5,'5.5 mm'),option(6,'6 mm'),option(6.5,'6.5 mm'),option(7,'7 mm'),option(7.5,'7.5 mm'),option(8,'8 mm'),option(8.5,'8.5 mm'),option(9,'9 mm'),option(9.5,'9.5 mm'),option(10,'10 mm'),option(10.5,'10.5 mm'),option(11,'11 mm'),option(11.5,'11.5 mm'),option(12,'12 mm'),option(12.5,'12.5 mm'),option(13,'13 mm'),option(13.5,'13.5 mm'),option(14,'14 mm'),option(14.5,'14.5 mm'),option(15,'15 mm'),option('na','Not applicable')],always).
question(cal_mm,periodontal,select,'Maximum interdental attachment loss',[option('unknown','Unknown'),option(0,'0 mm'),option(0.5,'0.5 mm'),option(1,'1 mm'),option(1.5,'1.5 mm'),option(2,'2 mm'),option(2.5,'2.5 mm'),option(3,'3 mm'),option(3.5,'3.5 mm'),option(4,'4 mm'),option(4.5,'4.5 mm'),option(5,'5 mm'),option(5.5,'5.5 mm'),option(6,'6 mm'),option(6.5,'6.5 mm'),option(7,'7 mm'),option(7.5,'7.5 mm'),option(8,'8 mm'),option(8.5,'8.5 mm'),option(9,'9 mm'),option(9.5,'9.5 mm'),option(10,'10 mm'),option(10.5,'10.5 mm'),option(11,'11 mm'),option(11.5,'11.5 mm'),option(12,'12 mm'),option(12.5,'12.5 mm'),option(13,'13 mm'),option(13.5,'13.5 mm'),option(14,'14 mm'),option(14.5,'14.5 mm'),option(15,'15 mm'),option('na','Not applicable')],always).
question(buccal_cal_mm,periodontal,select,'Maximum buccal/oral attachment loss',[option('unknown','Unknown'),option(0,'0 mm'),option(0.5,'0.5 mm'),option(1,'1 mm'),option(1.5,'1.5 mm'),option(2,'2 mm'),option(2.5,'2.5 mm'),option(3,'3 mm'),option(3.5,'3.5 mm'),option(4,'4 mm'),option(4.5,'4.5 mm'),option(5,'5 mm'),option(5.5,'5.5 mm'),option(6,'6 mm'),option(6.5,'6.5 mm'),option(7,'7 mm'),option(7.5,'7.5 mm'),option(8,'8 mm'),option(8.5,'8.5 mm'),option(9,'9 mm'),option(9.5,'9.5 mm'),option(10,'10 mm'),option(10.5,'10.5 mm'),option(11,'11 mm'),option(11.5,'11.5 mm'),option(12,'12 mm'),option(12.5,'12.5 mm'),option(13,'13 mm'),option(13.5,'13.5 mm'),option(14,'14 mm'),option(14.5,'14.5 mm'),option(15,'15 mm'),option('na','Not applicable')],always).
question(bop_percent,periodontal,select,'Sites bleeding on probing',[option('unknown','Unknown'),option(0,'0%'),option(5,'5%'),option(10,'10%'),option(15,'15%'),option(20,'20%'),option(25,'25%'),option(30,'30%'),option(35,'35%'),option(40,'40%'),option(45,'45%'),option(50,'50%'),option(55,'55%'),option(60,'60%'),option(65,'65%'),option(70,'70%'),option(75,'75%'),option(80,'80%'),option(85,'85%'),option(90,'90%'),option(95,'95%'),option(100,'100%'),option('na','Not applicable')],always).
question(nonadjacent_teeth,periodontal,radio,'Interdental loss at two nonadjacent teeth?',[option('unknown','Unknown'),option('yes','Yes'),option('no','No'),option('na','Not applicable')],always).
question(two_teeth,periodontal,radio,'Buccal/oral loss at two teeth?',[option('unknown','Unknown'),option('yes','Yes'),option('no','No'),option('na','Not applicable')],always).
question(nonperiodontal_causes,periodontal,radio,'Could another local cause account for the attachment loss?',[option('unknown','Unknown'),option('yes','Yes'),option('no','No'),option('na','Not applicable')],always).

question(bone_loss,periodontal,radio,'Dentist-interpreted alveolar bone loss?',[option(unknown,'Unknown'),option(yes,'Yes'),option(no,'No'),option(na,'Not applicable')],always).

valid_answer(Key, Value) :- question(Key,_,Type,_,Options,_), (Type == multi -> valid_multi(Value,Options) ; member(option(Allowed,_),Options), same_value(Value,Allowed)).
same_value(A,B) :- (number(A),number(B) -> A =:= B ; A == B).
valid_multi(Value,Options) :- memberchk(Value,[unknown,na,none]), member(option(Value,_),Options), !.
valid_multi(Value,Options) :- is_list(Value), Value \= [], sort(Value,Sorted), length(Value,N),length(Sorted,N), forall(member(V,Value),(atom(V),\+ memberchk(V,[unknown,na,none]),memberchk(option(V,_),Options))).
expand_observations(Obs, Expanded) :- (memberchk(obs(triggers,T),Obs) -> true ; T=unknown), findall(obs(Key,V),(member(Item-Key,[cold-trigger_cold,sweet-trigger_sweet,hot-trigger_hot]), selection_value(T,Item,V)),Extras),append(Obs,Extras,Expanded).
selection_value(none,_,no) :- !.
selection_value(na,_,na) :- !.
selection_value(List,Item,yes) :- is_list(List),memberchk(Item,List),!.
selection_value(_,_,unknown).
